
export const COUNTRY_LIST = [
    { name: "Morocco", code: "MA", dialCode: "+212", flag: "🇲🇦" },
    { name: "Afghanistan", code: "AF", dialCode: "+93", flag: "🇦🇫" },
    { name: "Albania", code: "AL", dialCode: "+355", flag: "🇦🇱" },
    { name: "Algeria", code: "DZ", dialCode: "+213", flag: "🇩🇿" },
    { name: "Andorra", code: "AD", dialCode: "+376", flag: "🇦🇩" },
    { name: "Angola", code: "AO", dialCode: "+244", flag: "🇦🇴" },
    { name: "Argentina", code: "AR", dialCode: "+54", flag: "🇦🇷" },
    { name: "Armenia", code: "AM", dialCode: "+374", flag: "🇦🇲" },
    { name: "Australia", code: "AU", dialCode: "+61", flag: "🇦🇺" },
    { name: "Austria", code: "AT", dialCode: "+43", flag: "🇦🇹" },
    { name: "Azerbaijan", code: "AZ", dialCode: "+994", flag: "🇦🇿" },
    { name: "Bahrain", code: "BH", dialCode: "+973", flag: "🇧🇭" },
    { name: "Bangladesh", code: "BD", dialCode: "+880", flag: "🇧🇩" },
    { name: "Belarus", code: "BY", dialCode: "+375", flag: "🇧🇾" },
    { name: "Belgium", code: "BE", dialCode: "+32", flag: "🇧🇪" },
    { name: "Belize", code: "BZ", dialCode: "+501", flag: "🇧🇿" },
    { name: "Benin", code: "BJ", dialCode: "+229", flag: "🇧🇯" },
    { name: "Bolivia", code: "BO", dialCode: "+591", flag: "🇧🇴" },
    { name: "Bosnia and Herzegovina", code: "BA", dialCode: "+387", flag: "🇧🇦" },
    { name: "Brazil", code: "BR", dialCode: "+55", flag: "🇧🇷" },
    { name: "Bulgaria", code: "BG", dialCode: "+359", flag: "🇧🇬" },
    { name: "Burkina Faso", code: "BF", dialCode: "+226", flag: "🇧🇫" },
    { name: "Cambodia", code: "KH", dialCode: "+855", flag: "🇰🇭" },
    { name: "Cameroon", code: "CM", dialCode: "+237", flag: "🇨🇲" },
    { name: "Canada", code: "CA", dialCode: "+1", flag: "🇨🇦" },
    { name: "Cape Verde", code: "CV", dialCode: "+238", flag: "🇨🇻" },
    { name: "Central African Republic", code: "CF", dialCode: "+236", flag: "🇨🇫" },
    { name: "Chad", code: "TD", dialCode: "+235", flag: "🇹🇩" },
    { name: "Chile", code: "CL", dialCode: "+56", flag: "🇨🇱" },
    { name: "China", code: "CN", dialCode: "+86", flag: "🇨🇳" },
    { name: "Colombia", code: "CO", dialCode: "+57", flag: "🇨🇴" },
    { name: "Comoros", code: "KM", dialCode: "+269", flag: "🇰🇲" },
    { name: "Congo", code: "CG", dialCode: "+242", flag: "🇨🇬" },
    { name: "Costa Rica", code: "CR", dialCode: "+506", flag: "🇨🇷" },
    { name: "Croatia", code: "HR", dialCode: "+385", flag: "🇭🇷" },
    { name: "Cuba", code: "CU", dialCode: "+53", flag: "🇨🇺" },
    { name: "Cyprus", code: "CY", dialCode: "+357", flag: "🇨🇾" },
    { name: "Czech Republic", code: "CZ", dialCode: "+420", flag: "🇨🇿" },
    { name: "Denmark", code: "DK", dialCode: "+45", flag: "🇩🇰" },
    { name: "Djibouti", code: "DJ", dialCode: "+253", flag: "🇩🇯" },
    { name: "Ecuador", code: "EC", dialCode: "+593", flag: "🇪🇨" },
    { name: "Egypt", code: "EG", dialCode: "+20", flag: "🇪🇬" },
    { name: "El Salvador", code: "SV", dialCode: "+503", flag: "🇸🇻" },
    { name: "Equatorial Guinea", code: "GQ", dialCode: "+240", flag: "🇬🇶" },
    { name: "Estonia", code: "EE", dialCode: "+372", flag: "🇪🇪" },
    { name: "Ethiopia", code: "ET", dialCode: "+251", flag: "🇪🇹" },
    { name: "Finland", code: "FI", dialCode: "+358", flag: "🇫🇮" },
    { name: "France", code: "FR", dialCode: "+33", flag: "🇫🇷" },
    { name: "Gabon", code: "GA", dialCode: "+241", flag: "🇬🇦" },
    { name: "Gambia", code: "GM", dialCode: "+220", flag: "🇬🇲" },
    { name: "Georgia", code: "GE", dialCode: "+995", flag: "🇬🇪" },
    { name: "Germany", code: "DE", dialCode: "+49", flag: "🇩🇪" },
    { name: "Ghana", code: "GH", dialCode: "+233", flag: "🇬🇭" },
    { name: "Greece", code: "GR", dialCode: "+30", flag: "🇬🇷" },
    { name: "Guinea", code: "GN", dialCode: "+224", flag: "🇬🇳" },
    { name: "Haiti", code: "HT", dialCode: "+509", flag: "🇭🇹" },
    { name: "Honduras", code: "HN", dialCode: "+504", flag: "🇭🇳" },
    { name: "Hong Kong", code: "HK", dialCode: "+852", flag: "🇭🇰" },
    { name: "Hungary", code: "HU", dialCode: "+36", flag: "🇭🇺" },
    { name: "Iceland", code: "IS", dialCode: "+354", flag: "🇮🇸" },
    { name: "India", code: "IN", dialCode: "+91", flag: "🇮🇳" },
    { name: "Indonesia", code: "ID", dialCode: "+62", flag: "🇮🇩" },
    { name: "Iran", code: "IR", dialCode: "+98", flag: "🇮🇷" },
    { name: "Iraq", code: "IQ", dialCode: "+964", flag: "🇮🇶" },
    { name: "Ireland", code: "IE", dialCode: "+353", flag: "🇮🇪" },
    { name: "Israel", code: "IL", dialCode: "+972", flag: "🇮🇱" },
    { name: "Italy", code: "IT", dialCode: "+39", flag: "🇮🇹" },
    { name: "Ivory Coast", code: "CI", dialCode: "+225", flag: "🇨🇮" },
    { name: "Japan", code: "JP", dialCode: "+81", flag: "🇯🇵" },
    { name: "Jordan", code: "JO", dialCode: "+962", flag: "🇯🇴" },
    { name: "Kazakhstan", code: "KZ", dialCode: "+7", flag: "🇰🇿" },
    { name: "Kenya", code: "KE", dialCode: "+254", flag: "🇰🇪" },
    { name: "Kuwait", code: "KW", dialCode: "+965", flag: "🇰🇼" },
    { name: "Lebanon", code: "LB", dialCode: "+961", flag: "🇱🇧" },
    { name: "Libya", code: "LY", dialCode: "+218", flag: "🇱🇾" },
    { name: "Luxembourg", code: "LU", dialCode: "+352", flag: "🇱🇺" },
    { name: "Malaysia", code: "MY", dialCode: "+60", flag: "🇲🇾" },
    { name: "Maldives", code: "MV", dialCode: "+960", flag: "🇲🇻" },
    { name: "Mali", code: "ML", dialCode: "+223", flag: "🇲🇱" },
    { name: "Mauritania", code: "MR", dialCode: "+222", flag: "🇲🇷" },
    { name: "Mexico", code: "MX", dialCode: "+52", flag: "🇲🇽" },
    { name: "Monaco", code: "MC", dialCode: "+377", flag: "🇲🇨" },
    { name: "Montenegro", code: "ME", dialCode: "+382", flag: "🇲🇪" },
    { name: "Netherlands", code: "NL", dialCode: "+31", flag: "🇳🇱" },
    { name: "New Zealand", code: "NZ", dialCode: "+64", flag: "🇳🇿" },
    { name: "Niger", code: "NE", dialCode: "+227", flag: "🇳🇪" },
    { name: "Nigeria", code: "NG", dialCode: "+234", flag: "🇳🇬" },
    { name: "Norway", code: "NO", dialCode: "+47", flag: "🇳🇴" },
    { name: "Oman", code: "OM", dialCode: "+968", flag: "🇴🇲" },
    { name: "Pakistan", code: "PK", dialCode: "+92", flag: "🇵🇰" },
    { name: "Palestine", code: "PS", dialCode: "+970", flag: "🇵🇸" },
    { name: "Panama", code: "PA", dialCode: "+507", flag: "🇵🇦" },
    { name: "Paraguay", code: "PY", dialCode: "+595", flag: "🇵🇾" },
    { name: "Peru", code: "PE", dialCode: "+51", flag: "🇵🇪" },
    { name: "Philippines", code: "PH", dialCode: "+63", flag: "🇵🇭" },
    { name: "Poland", code: "PL", dialCode: "+48", flag: "🇵🇱" },
    { name: "Portugal", code: "PT", dialCode: "+351", flag: "🇵🇹" },
    { name: "Qatar", code: "QA", dialCode: "+974", flag: "🇶🇦" },
    { name: "Romania", code: "RO", dialCode: "+40", flag: "🇷🇴" },
    { name: "Russia", code: "RU", dialCode: "+7", flag: "🇷🇺" },
    { name: "Saudi Arabia", code: "SA", dialCode: "+966", flag: "🇸🇦" },
    { name: "Senegal", code: "SN", dialCode: "+221", flag: "🇸🇳" },
    { name: "Serbia", code: "RS", dialCode: "+381", flag: "🇷🇸" },
    { name: "Singapore", code: "SG", dialCode: "+65", flag: "🇸🇬" },
    { name: "Slovakia", code: "SK", dialCode: "+421", flag: "🇸🇰" },
    { name: "South Africa", code: "ZA", dialCode: "+27", flag: "🇿🇦" },
    { name: "South Korea", code: "KR", dialCode: "+82", flag: "🇰🇷" },
    { name: "Spain", code: "ES", dialCode: "+34", flag: "🇪🇸" },
    { name: "Sweden", code: "SE", dialCode: "+46", flag: "🇸🇪" },
    { name: "Switzerland", code: "CH", dialCode: "+41", flag: "🇨🇭" },
    { name: "Thailand", code: "TH", dialCode: "+66", flag: "🇹🇭" },
    { name: "Tunisia", code: "TN", dialCode: "+216", flag: "🇹🇳" },
    { name: "Turkey", code: "TR", dialCode: "+90", flag: "🇹🇷" },
    { name: "Ukraine", code: "UA", dialCode: "+380", flag: "🇺🇦" },
    { name: "United Arab Emirates", code: "AE", dialCode: "+971", flag: "🇦🇪" },
    { name: "United Kingdom", code: "GB", dialCode: "+44", flag: "🇬🇧" },
    { name: "United States", code: "US", dialCode: "+1", flag: "🇺🇸" },
    { name: "Vietnam", code: "VN", dialCode: "+84", flag: "🇻🇳" },
    { name: "Yemen", code: "YE", dialCode: "+967", flag: "🇾🇪" }
];
